services:
  web_corex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corex
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 7777
      HOSTNAME: 0.0.0.0
    ports:
      - "7777:7777"
    networks:
      - corex_net

networks:
  corex_net:
    name: corex_net
    driver: bridge
